apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homelab-dashboard.frontendName" . }}
  labels:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: homelab-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "{{ .Values.frontend.env.BACKEND_URL }}"
