apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homelab-dashboard.backendName" . }}
  labels:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: homelab-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 3001
