{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homelab-dashboard.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: frontend
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homelab-dashboard.frontendName" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .hosts | join " " }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
