apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-dashboard.backendName" . }}
  labels:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 3001
