apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-dashboard.frontendName" . }}
  labels:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "homelab-dashboard.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 3000
